alias l='ls -lF'
alias ll='ls -alF'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias temp='vcgencmd measure_temp'
alias cpv='rsync -ah --info=progress2'
alias sha1='openssl sha1'
alias diff='colordiff'
alias mount='mount |column -t'
alias now='date +"%r"'
alias nowtime=now
alias nowdate='date +"%A, %B %d, %Y (%D)"'
alias vi=vim
alias ports='netstat -tulanp'
alias c='clear'
alias reboot='sudo reboot'
alias restart='sudo reboot'
alias update='sudo apt update && sudo apt upgrade'
alias apt='sudo apt'
alias cpuinfo='lscpu'
alias meminfo='free -m -l -t'
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
alias wget='wget -c'
alias df='df -H'
alias du='du -ch'
alias top='atop'
alias bitdefender='sudo bitdefender'
alias scannfull='sudo bitdefender scan -s full'
alias scan='sudo bitdefender scan -s custom'
set fish_greeting ""
