#!/bin/bash

cd /home/tsadmin/teomaremote
sudo -u tsadmin git pull
./install.sh --update

current_date=$(date +%m-%d-%Y)

XMLPath=$(find /root/.mono/registry -name "values.xml")
XMLTemp=$(cat $XMLPath | grep -v "</values>")
XMLTemp="$XMLTemp"$'\n'"<value name=\"Custom27\" type=\"string\">Last System Update: $current_date</value>"$'\n'"</values>"
rm $XMLPath
echo "$XMLTemp" >> $XMLPath
